name: Univalence Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run formatting
        run: sbt "project newZioSpark" scalafmtCheck
      - name: Run linting
        run: sbt "project newZioSpark" "scalafix --check"
      - name: Run tests
        run: sbt "project newZioSpark" clean coverage test
      - name: Generate coverage report
        run: sbt "project newZioSpark" coverageReport
      - name: Publish coverage to codecov
        uses: codecov/codecov-action@v2